name: data-pipeline-workflow

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "35 0 * * *"

jobs: 
  run-data-pipeline:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data pipeline
        env: 
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: python data_pipeline.py

      - name: Check changes
        id: git-check
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git diff --stage --quiet || echo "changes=true" >>$GITHUB_ENV

      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "updated the video index"
          git push


